# Generated by Django 5.0 on 2023-12-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned_by', models.TextField(blank=True, max_length=150, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('wallet_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_user', to='wallet_service.customer')),
            ],
            options={
                'db_table': 'wallet_details',
            },
        ),
    ]
