# Generated by Django 5.0 on 2023-12-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_service', '0003_wallettransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdrawal')], default='deposit', max_length=10),
        ),
    ]
